language: python
python:
  - 2.6
  - 2.7
install:
  - if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then
      # For Python 2.7 we can install binary packages with apt-get
      # We use this to check the notebooks
      - deactivate;
      - time sudo apt-get install -qq python-nose python-matplotlib ipython-notebook cython;
    fi
  #- time pip install ipython[zmq,notebook] --use-mirrors
  #- time pip install cython --use-mirrors
script:
  - time python setup.py build_ext -i
  - time nosetests

  - if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then
      - time python setup.py install;
      - cd tutorial;
      - time ../devscripts/checkipnb.py tutorial.ipynb;
      - time ../devscripts/checkipnb.py hard-core-tutorial.ipynb;
    fi
