language: python
python:
  - 2.6
  - 2.7
install:
  - time pip install ipython[zmq,notebook]
script:
  - time python setup.py build_ext -i
  - time nosetests
  # Check that the tutorial notebooks run without error
  - time python setup.py install
  - cd tutorial
  - time ../devscripts/checkipnb.py tutorial.ipynb
  # TODO: The .py scripts don't run at the moment.
  # https://github.com/iminuit/iminuit/issues/2
  # When they do add this test:
  #- python tutorial.py
